[[redirects]]
  from = "/:namespace/:notebook/"
  to = "https://api.observablehq.com/:namespace/:notebook.js?v=3"
  status = 200

[[edge_functions]]
  path = "/:namespace/:notebook/"
  function = "obs"